import Card, { CardContent } from "material-ui/Card";
import Typography from "material-ui/Typography";
import React, { Component } from "react";
import ComponentWrappers from "../../ComponentWrappers";
import rep from "./calender-512.png";

class Welcome extends Component {
  render() {
    return (
      <div style={{ display: "flex", margin: "auto", flexFlow: "row wrap" }}>
        <Card
          style={{
            margin: "48px",
            height: "auto",
            maxWidth: "256px",
            display: "flex",
            flex: 1,
            objectFit: "contain",
          }}
        >

          <img
            src={rep}
            alt="An illustration of a red calender"
            style={{ minWidth: "128px", maxWidth: "256px", height: "auto", objectFit: "contain" }}
          />

        </Card>

        <Card
          style={{
            margin: "48px",
            maxWidth: "70%",
            display: "flex",
            flex: 4
          }}
        >
          <CardContent>
            <Typography type="headline" component="h1">
              Welcome to this Timetable Generator
            </Typography>
            <Typography type="body1" color="secondary"></Typography>
            <hr />
            <br />
            <Typography component="p">
              A Timetable Generator capable of auto-generating separate timetable
              for Teachers and subjects in the Institute based on the Class
              timetable created / auto-generated by the user.
              <br />
              <br />
              This will allow the users to create and modify timetables easily and
              have them hosted online so that they can be retrieved anytime.
            </Typography>
          </CardContent>
        </Card>
      </div>
    );
  }
}

export default ComponentWrappers(Welcome);
